### ISSUE TITLE
Throughput && fetch_add && version chain storage

### ISSUE THREAD

**Issue by xiangyiwen** [thawk105/ccbench#12]
An Analysis of Concurrency Control Protocols for In-Memory Databases with CCBench is really a great paper.
After reading it, I have three questions which confuse me a lot. If you could give me some answers, I'll be very appreciated.
1. In your experiments, you count the number of committed and aborted transactions as the average throughput. Then you how can you determine that after using ReadPhaseExtension, the throughput improvement of CC is not caused by the large count of aborted transactions? And whether it's reasonable to include the number of aborted transactions in the throughput?
2. How  do you measure the throughput of fetch_add? And how do you measure the latency breakdown of the Cicada operations?
3. How do you store the versions in your version chain? Are the versions organized in the new version to the old version way or in the old version to the new version way?

**Comment by thawk105** [comment]
Thank you for reading our paper :)
1. This question is a little bit confusing... Anyhow we do not include the number of aborted transactions to the throughput.

2. All worker threads called fetch_add concurrently in a tight loop that incremented the shared counter. The throughput is calculated as the shared counter value at the end of execution divided by the execution time.
We use Time Stamp Counter [1] to measure the latency breakdown of the Cicada operations.
We measured the latency of calls of each procedure and accumulated them during the experiment. After that, we got the percentage of the several procedures using the accumulated latency of them.

3. We use CAS operations.
Please look at the codes around below.
https://github.com/thawk105/ccbench/blob/51392fc609dd85ab2395decdac24de412079829c/cicada/transaction.cc#L348
Ours and original (authors of Cicada) team's use organizations which is the new version to the old version way.
Pleas look at the Cicada paper's sentence "The version list is sorted by wts of the versions, forming latest-to-earliest order from the head." at section 3.2.

[1] Intel 64 and IA-32 Architectures Developer’s Manual: Vol. 2B. http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-2b-manual.pdf, 2016.

**Comment by xiangyiwen** [comment]
Thank you so much for your detailed answers! That really helps me a lot!
Firstly, I'm sorry for my mistake in describing question one. After reviewing your paper, I find that you counted the number of committed and aborted transactions to calculate average throughput indeed.(I misunderstood that you counted the number of committed and aborted transactions as average throughput.) 
Secondly, according to your first answer, I want to confirm that whether the throughput in your experiments only included committed transactions or not? If not, what is the throughput actually composed of?
Again, thank you for your kindness and clear answers！

**Comment by thawk105** [comment]
>> I want to confirm that whether the throughput in your experiments only included committed transactions or not?
Yes. We use the word "throughput" as the number of committed transactions per specific time (specific is usually one second).

If you have some other questions, you don't have to hesitate to ask us.

**Comment by xiangyiwen** [comment]
Thank you for your great kindness! I'll consult you if I have some other questions.
