### ISSUE TITLE
L3 cache miss

### ISSUE THREAD

**Issue by xiangyiwen** [thawk105/ccbench#13]
How did you evaluate the L3 cache miss in your experiments? If you could explain in detail, I'll be extremely appreciative of your kindness!!!

**Comment by thawk105** [comment]
We used perf command.
Please look below codes.
https://github.com/thawk105/ccbench/blob/f3e634a8f8ffe9b2a9fdf1211568ca1d4cd64aff/cicada/script/ycsb-xth.sh#L78

And the cache-miss data which was used for paper is extracted at below.
https://github.com/thawk105/ccbench/blob/f3e634a8f8ffe9b2a9fdf1211568ca1d4cd64aff/cicada/script/ycsb-xth.sh#L83
