### ISSUE TITLE
Is MVCC supported?

### ISSUE THREAD

**Issue by xuebinsu** [thawk105/ccbench#9]
Mltiversion Concurrency Control (MVCC) is a family of widely-adopted CC protocols including MV2PL and MVOCC. Would be nice if those protocols are supported.

**Comment by thawk105** [comment]
Thanks for your comment.

CCBench support Cicada, SI, ermia (in CCBench, this is SI & latch-free SSN) as MVCC. I think it is good to expand MV2PL and MVOCC to improve the quality of the evaluation platform. If I can afford it, I would like to do such an extension.
